# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../network/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../network/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../network/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.producer.example.com:
    container_name: peer0.producer.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.producer.example.com
      - CORE_PEER_ADDRESS=peer0.producer.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.producer.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.producer.example.com:8051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../network/crypto-config/peerOrganizations/producer.example.com/peers/peer0.producer.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network/crypto-config/peerOrganizations/producer.example.com/peers/peer0.producer.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.producer.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
      
  peer1.producer.example.com:
    container_name: peer1.producer.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.producer.example.com
      - CORE_PEER_ADDRESS=peer1.producer.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.producer.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.producer.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.producer.example.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../network/crypto-config/peerOrganizations/producer.example.com/peers/peer1.producer.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network/crypto-config/peerOrganizations/producer.example.com/peers/peer1.producer.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.producer.example.com:/var/hyperledger/production
    ports:
      - 8051:8051    
  
  peer0.manufacturer.example.com:
    container_name: peer0.manufacturer.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.manufacturer.example.com
      - CORE_PEER_ADDRESS=peer0.manufacturer.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.manufacturer.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.manufacturer.example.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manufacturer.example.com:9051
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../network/crypto-config/peerOrganizations/manufacturer.example.com/peers/peer0.manufacturer.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network/crypto-config/peerOrganizations/manufacturer.example.com/peers/peer0.manufacturer.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.manufacturer.example.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer0.distributor.example.com:
    container_name: peer0.distributor.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.distributor.example.com
      - CORE_PEER_ADDRESS=peer0.distributor.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.distributor.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.distributor.example.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.distributor.example.com:10051
      - CORE_PEER_LOCALMSPID=DistributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../network/crypto-config/peerOrganizations/distributor.example.com/peers/peer0.distributor.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network/crypto-config/peerOrganizations/distributor.example.com/peers/peer0.distributor.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.distributor.example.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.retailer.example.com:
    container_name: peer0.retailer.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.retailer.example.com
      - CORE_PEER_ADDRESS=peer0.retailer.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.retailer.example.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.retailer.example.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.retailer.example.com:12051
      - CORE_PEER_LOCALMSPID=RetailerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../network/crypto-config/peerOrganizations/retailer.example.com/peers/peer0.retailer.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network/crypto-config/peerOrganizations/retailer.example.com/peers/peer0.retailer.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.retailer.example.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.retailer.example.com:
    container_name: peer1.retailer.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.retailer.example.com
      - CORE_PEER_ADDRESS=peer1.retailer.example.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.retailer.example.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.retailer.example.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.retailer.example.com:11051
      - CORE_PEER_LOCALMSPID=RetailerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../network/crypto-config/peerOrganizations/retailer.example.com/peers/peer1.retailer.example.com/msp:/etc/hyperledger/fabric/msp
        - ../network/crypto-config/peerOrganizations/retailer.example.com/peers/peer1.retailer.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.retailer.example.com:/var/hyperledger/production
    ports:
      - 12051:12051

  peer0.consumer.example.com:
      container_name: peer0.consumer.example.com
      extends:
        file: peer-base.yaml
        service: peer-base
      environment:
        - CORE_PEER_ID=peer0.consumer.example.com
        - CORE_PEER_ADDRESS=peer0.consumer.example.com:13051
        - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
        - CORE_PEER_CHAINCODEADDRESS=peer0.consumer.example.com:13052
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.consumer.example.com:13051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consumer.example.com:14051
        - CORE_PEER_LOCALMSPID=ConsumerMSP
      volumes:
          - /var/run/:/host/var/run/
          - ../network/crypto-config/peerOrganizations/consumer.example.com/peers/peer0.consumer.example.com/msp:/etc/hyperledger/fabric/msp
          - ../network/crypto-config/peerOrganizations/consumer.example.com/peers/peer0.consumer.example.com/tls:/etc/hyperledger/fabric/tls
          - peer0.consumer.example.com:/var/hyperledger/production
      ports:
        - 13051:13051
        
  peer1.consumer.example.com:
      container_name: peer1.consumer.example.com
      extends:
        file: peer-base.yaml
        service: peer-base
      environment:
        - CORE_PEER_ID=peer1.consumer.example.com
        - CORE_PEER_ADDRESS=peer1.consumer.example.com:14051
        - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
        - CORE_PEER_CHAINCODEADDRESS=peer1.consumer.example.com:14052
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.consumer.example.com:14051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.example.com:13051
        - CORE_PEER_LOCALMSPID=ConsumerMSP
      volumes:
          - /var/run/:/host/var/run/
          - ../network/crypto-config/peerOrganizations/consumer.example.com/peers/peer1.consumer.example.com/msp:/etc/hyperledger/fabric/msp
          - ../network/crypto-config/peerOrganizations/consumer.example.com/peers/peer1.consumer.example.com/tls:/etc/hyperledger/fabric/tls
          - peer1.consumer.example.com:/var/hyperledger/production
      ports:
        - 14051:14051
