OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    
    Specs:
      - Hostname: orderer
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1 : Producer
  # ---------------------------------------------------------------------------
  - Name: Producer
    Domain: producer.example.com

    #CA:
    #   Hostname: ca # implicitly ca.producer.example.com

    EnableNodeOUs: true

    Template:
      Count: 2
    Users:
      Count: 2
      
  - Name: Manufacturer
    Domain: manufacturer.example.com

    #CA:
    #   Hostname: ca # implicitly ca.manufacturer.example.com

    EnableNodeOUs: true

    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Distributor
    Domain: distributor.example.com

    #CA:
    #   Hostname: ca # implicitly ca.distributor.example.com

    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Retailer
    Domain: retailer.example.com

    #CA:
    #   Hostname: ca # implicitly ca.retailer.example.com

    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
      
  # ---------------------------------------------------------------------------
  # Org: Consumer
  # ---------------------------------------------------------------------------
  - Name: Consumer
    Domain: consumer.example.com

    #CA:
    #   Hostname: ca # implicitly ca.consumer.example.com

    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
